In [1]:
import numpy as np
import pandas as pd

%matplotlib inline
import matplotlib.pyplot as plt

##  Работа с текстовыми данными 
Будем работать с данными с семинара, но использовать все категории текстов:

In [2]:
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train',shuffle=True,random_state=7)
twenty_test = fetch_20newsgroups(subset='test', shuffle=True,random_state=7)#

In [3]:
X_train=twenty_train.data
X_test=twenty_test.data
y_train=twenty_train.target
y_test=twenty_test.target

### 1. Мешок слов (1 балл)
Воспользуйтесь мешком слов  для признакового описания документа. Постройте логистическую регрессию с параметрами по умолчанию.  Какова доля верных предсказаний на тестовой выборке?

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [22]:
pipeline = Pipeline([
('vect', CountVectorizer()),
('clf', LogisticRegression()),
])
pipeline.fit(X_train,y_train)
y_pred = pipeline.predict(X_test)

In [23]:
print(metrics.accuracy_score(y_test, y_pred))

0.8069569835369091

### 2. TF-IDF (1 балл)
Теперь в качестве признаков возьмите величины tf-idf. Как поменялось качество классификатора?

In [125]:
pipeline = Pipeline([
('vect', CountVectorizer()),
('tfidf', TfidfTransformer()),
('clf', LogisticRegression()),
])
pipeline.fit(X_train,y_train)
y_pred = pipeline.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [25]:
print(metrics.accuracy_score(y_test,y_pred))

0.8279341476367499

Классификатор стал давать более точные предсказания

### 3.  Матрица ошибок (1 балл)
Выведите матрицу ошибок. Определите три пары категорий, которые модель путает чаще всего.

In [54]:
conf_matrix = pd.DataFrame(data = metrics.confusion_matrix(y_test,y_pred))

conf_matrix

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,236,2,0,0,1,1,3,0,3,3,1,1,2,9,2,35,3,4,1,12
1,2,304,13,8,8,19,7,1,0,1,0,4,10,1,5,2,1,1,1,1
2,1,21,294,31,12,10,2,2,1,5,0,1,1,2,4,2,0,0,4,1
3,0,12,24,283,22,2,13,3,1,1,1,1,24,0,4,0,0,0,0,1
4,0,5,6,21,319,1,11,1,1,5,1,0,10,0,1,0,0,0,3,0
5,0,41,38,5,4,292,3,0,1,1,0,1,3,2,4,0,0,0,0,0
6,0,3,2,12,7,0,351,3,2,1,1,0,7,1,0,0,0,0,0,0
7,0,1,1,4,0,2,12,352,4,2,0,0,13,1,1,0,1,0,2,0
8,0,0,0,0,0,0,6,10,379,2,0,0,1,0,0,0,0,0,0,0
9,1,0,0,0,2,0,6,1,0,368,15,0,2,0,0,0,1,0,0,1
10,0,0,0,1,3,1,2,0,0,9,382,0,0,0,0,0,0,0,1,0
11,1,7,3,0,3,4,5,2,1,5,0,352,5,0,1,0,4,0,3,0
12,1,9,5,20,9,4,8,5,2,3,0,10,307,4,5,1,0,0,0,0
13,4,10,1,2,2,2,13,1,5,4,0,0,11,331,0,3,1,3,3,0
14,0,11,0,0,2,1,2,1,0,0,1,0,2,6,363,1,2,0,2,0
15,4,4,2,1,0,1,1,0,0,2,0,0,2,1,3,371,0,0,0,6
16,0,0,0,1,1,0,5,3,2,4,1,5,1,4,2,0,326,1,7,1
17,7,2,0,0,0,9,1,1,1,3,1,1,0,0,0,3,3,333,11,0
18,1,2,0,0,1,1,4,1,2,0,0,2,2,4,8,4,97,2,179,0
19,38,4,0,0,0,0,4,0,0,2,2,0,0,8,3,48,17,2,9,114

Вот на этом моменте я остановился на семинаре. Вы вроде бы говорили отметить, если каккая-то часть задания была сделана на семинаре.

In [102]:
dat = metrics.confusion_matrix(y_test,y_pred)
ans = {}
for i in range(len(conf_matrix[0])):
    dat[i,i] = -1
    ans[np.max(dat[i])] = [i, np.argmax(dat[i])]

for i in range(3):
    bmax = max(ans.keys())
    bufm = ans.pop(bmax)
    print(i+1, "pair is ",twenty_test.target_names[bufm[0]]," and ",twenty_test.target_names[bufm[1]])

1 pair is  talk.politics.misc  and  talk.politics.guns
2 pair is  talk.religion.misc  and  soc.religion.christian
3 pair is  comp.windows.x  and  comp.graphics

### 4.Определение наиболее важных признаков (слов) (2 балла)
Выберите категорию. Для гиперплоскости, отделяющей класс этой категории от остальных, определите 5 признаков, которые имеют наибольшие коэффициенты в линейной модели и 5 признаков, которые имеют наименьшие коэффициенты:
* определите слова, котором соответствуют наибольшие и наименьшие коэффициенты в линейной модели;
* напишите  функцию поиска ключа в словаре по заданному листу значений.

In [152]:
category = 7
print("Chosen category is called ", twenty_test.target_names[category])
clf_param = pipeline.get_params()['clf']
dictionary = pipeline.get_params()['steps'][0][1].vocabulary_
val = list(dictionary.values())
answ = list(dictionary.keys())
 
coefs = clf_param.coef_[category].copy()
min_buf = clf_param.coef_[category].mean()
max_buf = clf_param.coef_[category].mean()
print("Max: " , end = '')

for i in range(5):
    n = np.argmax(coefs)
    m_ind = val.index(n)
    print(answ[m_ind] , end = ' ')
    coefs[n] = min_buf
print()
print("Min: " , end = '')
for i in range(5):
    n = np.argmin(coefs)
    m_ind = val.index(n)
    print(answ[m_ind] , end = ' ')
    coefs[n] = max_buf

Chosen category is called  rec.autos
Max: car cars engine oil dealer
Min: of to bike is god

In [153]:
def key_by_value(vocab, lst):
    val=[]
    for i in lst:
        val.append(list(vocab.keys())[list(vocab.values()).index(i)])
    return val

In [154]:
lst = [61674 , 43537, 75166]
print(key_by_value(dictionary, lst))

['half', 'cross', 'leg']